#!/usr/bin/env python

import json
from numbers import Number
import sys
from compiler.ast import flatten

def main():
    template = json.load(sys.stdin)

    (graph, edges) = extract_graph(template.get('Description', ''), template['Resources'])
    graph['edges'].extend(edges)
    handle_terminals(template, graph, 'Parameters', 'source')
    handle_terminals(template, graph, 'Outputs', 'sink')
    graph['subgraphs'].append(handle_psuedo_params(graph['edges']))

    render(graph)

def handle_terminals(template, graph, name, rank):
    if name in template:
        (subgraph, edges) = extract_graph(name, template[name])
        subgraph['rank'] = rank
        subgraph['style'] = 'filled,rounded'
        graph['subgraphs'].append(subgraph)
        graph['edges'].extend(edges)

def handle_psuedo_params(edges):
    graph = {'name': 'Psuedo Parameters', 'nodes': [], 'edges': [], 'subgraphs': []}
    graph['shape'] = 'ellipse'
    params = set()
    for e in edges:
        if e['from'].startswith(u'AWS::'):
            params.add(e['from'])
    graph['nodes'].extend({'name': n} for n in params)
    return graph

def extract_graph(name, elem):
    graph = {'name': name, 'nodes': [], 'edges': [], 'subgraphs': []}
    edges = []
    for item, details in elem.iteritems():
        d = {'name': item}
        for k in details.keys():
            if k.endswith('Policy') or k in ['Properties', 'Value']:
                d[k] = details[k]
        graph['nodes'].append(d)
        edges.extend(flatten(find_refs(item, details)))
    return (graph, edges)

from_to = {}

def find_refs(context, elem):
    if isinstance(elem, dict):
        refs = []
        for k, v in elem.iteritems():
            if unicode(k) == unicode('Ref'):
                assert isinstance(v, basestring), 'Expected a string: %s' % v
                if not from_to.has_key(v):
                    from_to[v] = []
                if not context in from_to[v]:
                    from_to[v].append(context)
                    refs.append({'from': v, 'to': context})
            elif unicode(k) == unicode('Fn::GetAtt'):
                assert isinstance(v, list), 'Expected a list: %s' % v
                if not from_to.has_key(v[0]):
                    from_to[v[0]] = []
                if not context in from_to[v[0]]:
                    refs.append({'from': v[0], 'to': context})
                    from_to[v[0]].append(context)
            else:
                refs.extend(find_refs(context, v))
        return refs
    elif isinstance(elem, list):
        return map(lambda e: find_refs(context, e), elem)
    elif isinstance(elem, basestring):
        return []
    elif isinstance(elem, bool):
        return []
    elif isinstance(elem, Number):
        return []
    else:
        raise AssertionError('Unexpected type: %s' % elem)

def render(graph, subgraph=False):
    print '%s "%s" {' % ('subgraph' if subgraph else 'digraph', graph['name'])
    print 'node [shape={}, fontsize=12];'.format(graph.get('shape', 'box'))
    if 'style' in graph:
        print 'node [style="%s"]' % graph['style']
    if 'rank' in graph:
        print 'rank=%s' % graph['rank']
    for n in graph['nodes']:
        tooltip = ""
        for k in n.keys():
            if k == 'name':
                continue
            p = json.dumps(n[k], indent=4, separators=(',', ': ')).replace('\\', '\\\\').replace('"', '\\"').replace('\n', '&#10;\n')
            tooltip += '%s: %s&#10;\n' % (k, p)
        if tooltip:
            print '"%s" [tooltip="%s"]' % (n['name'], tooltip)
        else:
            print '"%s"' % n['name']
    for s in graph['subgraphs']:
        render(s, True)
    for e in graph['edges']:
        print '"%s" -> "%s";' % (e['from'], e['to'])
    print '}'

def debug(*s):
    print >>sys.stderr, s

if __name__ == '__main__':
    main()
