TypeIconDir = 'simple-icons'
TypeIcon = {
    'AWS::AutoScaling::AutoScalingGroup': 'Compute/Compute_AmazonEC2_AutoScaling.svg',
    #'AWS::AutoScaling::LaunchConfiguration': 'AutoScalingLaunchConfig.svg',
    #'AWS::AutoScaling::LifecycleHook': 'AutoScalingLifecycleHook.svg',
    #'AWS::AutoScaling::ScalingPolicy': 'AutoScalingScalingPolicy.svg',
    #'AWS::AutoScaling::ScheduledAction': 'AutoScalingScheduledAction.svg',
    'AWS::ApiGateway::RestApi': 'Application Services/ApplicationServices_AmazonAPIGateway.svg',
    'AWS::ApiGateway::Method': 'Application Services/ApplicationServices_AmazonAPIGateway.svg',
    'AWS::ApiGateway::Deployment': 'Application Services/ApplicationServices_AmazonAPIGateway.svg',
    #'AWS::CloudFormation::CustomResource': 'CloudFormation.svg',
    #'AWS::CloudFormation::Stack': 'CloudFormationStack.svg',
    #'AWS::CloudFormation::WaitCondition': 'CloudFormation.svg',
    #'AWS::CloudFormation::WaitConditionHandle': 'CloudFormation.svg',
    'AWS::CloudFront::Distribution': 'Storage & Content Delivery/Storage-Content-Delivery_AmazonCloudFront_downloaddistribution.svg',
    'AWS::CloudTrail::Trail': 'Management Tools/Management-Tools_AWSCloudTrail.svg',
    'AWS::CloudWatch::Alarm': 'Management Tools/Management-Tools_AmazonCloudWatch_alarm.svg',
    'AWS::CodeDeploy::Application': 'Developer Tools/Developer-Tools_AWSCodeDeploy.svg',
    #'AWS::CodeDeploy::DeploymentConfig': 'CodeDeployDeploymentConfig.svg',
    'AWS::CodeDeploy::DeploymentGroup': 'Developer Tools/Developer-Tools_AWSCodeDeploy.svg',
    'AWS::DataPipeline::Pipeline': 'Analytics/Analytics_AWSDataPipeline.svg',
    'AWS::DirectoryService::SimpleAD': 'Security Identity & Compliance/Security-Identity_AWSDirectoryService.svg',
    'AWS::DynamoDB::Table': 'Database/Database_AmazonDynamoDB_table.svg',
    'AWS::EC2::CustomerGateway': 'Networking/Networking_AmazonVPC_customergateway.svg',
    #'AWS::EC2::DHCPOptions': 'EC2DHCPOptions.svg',
    'AWS::EC2::EIP': 'Compute/Compute_AmazonEC2_ElasticIP.svg',
    'AWS::EC2::Instance': 'Compute/Compute_AmazonEC2_instance.svg',
    'AWS::EC2::InternetGateway': 'Networking/Networking_AmazonVPC_internetgateway.svg',
    #'AWS::EC2::NetworkAcl': 'EC2NetworkAcl.svg',
    #'AWS::EC2::NetworkAclEntry': 'EC2NetworkAclEntry.svg',
    #'AWS::EC2::NetworkInterface': 'EC2NetworkInterface.svg',
    #'AWS::EC2::PlacementGroup': 'EC2PlacementGroup.svg',
    #'AWS::EC2::Route': 'EC2Route.svg',
    #'AWS::EC2::RouteTable': 'Route53RouteTable.svg',
    #'AWS::EC2::SecurityGroup': 'EC2SecurityGroup.svg',
    'AWS::EC2::SpotFleet': 'Compute/Compute_AmazonEC2.svg',
    'AWS::EC2::Subnet': 'Compute/Compute_AmazonEC2.svg',
    'AWS::EC2::Volume': 'Storage & Content Delivery/Storage-Content-Delivery_volume.svg',
    'AWS::EC2::VPC': 'Networking/Networking_AmazonVPC.svg',
    #'AWS::EC2::VPNConnectionRoute': 'VPNConnectionRoute.svg',
    'AWS::EC2::VPCEndpoint': 'Networking/Networking_AmazonVPC_endpoints.svg',
    'AWS::EC2::VPNGateway': 'Networking/Networking_AmazonVPC_VPNgateway.svg',
    'AWS::ECS::Cluster': 'General/General_AWScloud.svg',
    'AWS::ECS::Service': 'General/General_AWScloud.svg',
    'AWS::ECS::TaskDefinition': 'General/General_AWScloud.svg',
    'AWS::EFS::FileSystem': 'General/General_AWScloud.svg',
    'AWS::EFS::MountTarget': 'General/General_AWScloud.svg',
    'AWS::ElastiCache::CacheCluster': 'Database/Database_AmazonElasticCache.svg',
    'AWS::ElastiCache::ParameterGroup': 'Database/Database_AmazonElasticCache.svg',
    'AWS::ElastiCache::ReplicationGroup': 'Database/Database_AmazonElasticCache.svg',
    #'AWS::ElastiCache::SecurityGroup': 'ElasticCacheSecurityGroup.svg',
    #'AWS::ElastiCache::SecurityGroupIngress': 'ElasticCacheSecurityGroup.svg',
    #'AWS::ElastiCache::SubnetGroup': 'ElasticCacheSecurityGroup.svg',
    'AWS::ElasticBeanstalk::Application': 'Compute/Compute_AWSElasticBeanstalk_application.svg',
    'AWS::ElasticBeanstalk::ApplicationVersion': 'ElasticBeanstalkApplication.svg',
    #'AWS::ElasticBeanstalk::ConfigurationTemplate': 'ElasticBeanstalkConfigurationTemplate.svg',
    'AWS::ElasticBeanstalk::Environment': 'Compute/Compute_AWSElasticBeanstalk.svg',
    'AWS::ElasticLoadBalancing::LoadBalancer': 'Compute/Compute_ElasticLoadBalancing.svg',
    'AWS::IAM::AccessKey': 'Security Identity & Compliance/Security-Identity_AWSIAM.svg',
    'AWS::IAM::Group': 'Security Identity & Compliance/Security-Identity_AWSIAM.svg',
    'AWS::IAM::InstanceProfile': 'Security Identity & Compliance/Security-Identity_AWSIAM.svg',
    #'AWS::IAM::ManagedPolicy': 'ManagedPolicy.svg',
    #'AWS::IAM::Policy': 'Policy.svg',
    'AWS::IAM::Role': 'Security Identity & Compliance/SecurityIdentityCompliance_IAM_role.svg',
    'AWS::IAM::User': 'General/General_user.svg',
    #'AWS::IAM::UserToGroupAddition': 'IAMUserToGroupAddition.svg',
    'AWS::Kinesis::Stream': 'Application Services/Application-Services_AmazonAppStream.svg',
    'AWS::Lambda::Function': 'Compute/Compute_AWSLambda.svg',
    'AWS::Lambda::Permission': 'Security Identity & Compliance/SecurityIdentityCompliance_IAM_permissions.svg',
    #'AWS::Lambda::EventSourceMapping': 'LambdaEventSourceMapping.svg',
    'AWS::Serverless::Function': 'Compute/Compute_AWSLambda.svg',
    'AWS::Logs::LogGroup': 'General/General_AWScloud.svg',
    'AWS::Logs::MetricFilter': 'General/General_AWScloud.svg',
    'AWS::OpsWorks::App': 'Management Tools/Management-Tools_AWSOpsWorks_apps.svg',
    'AWS::OpsWorks::Instance': 'Management Tools/Management-Tools_AWSOpsWorks_instances.svg',
    'AWS::OpsWorks::Layer': 'Management Tools/Management-Tools_AWSOpsWorks_layers.svg',
    'AWS::OpsWorks::Stack': 'Management Tools/Management-Tools_AWSOpsWorks_stack.svg',
    'AWS::RDS::DBInstance': 'Database/Database_AmazonRDS_RDSDBinstance.svg',
    'AWS::RDS::DBParameterGroup': 'Database/Database_AmazonRDS.svg',
    #'AWS::RDS::DBSecurityGroup': 'RDSDBSecurityGroup.svg',
    'AWS::RDS::DBSubnetGroup': 'Database/Database_AmazonRDS.svg',
    #'AWS::RDS::DBClusterParameterGroup': 'AmazonRDS_Cluster.svg',
    'AWS::RDS::EventSubscription': 'Database/Database_AmazonRDS.svg',
    'AWS::RDS::OptionGroup': 'Database/Database_AmazonRDS.svg',
    #'AWS::RDS::DBCluster': 'AmazonRDS_Cluster.svg',
    'AWS::Redshift::Cluster': 'RedshiftDW2Cluster.svg',
    'AWS::Redshift::ClusterParameterGroup': 'General/General_AWScloud.svg',
    #'AWS::Redshift::ClusterSecurityGroup': 'RedshiftClusterSecurityGroup.svg',
    #'AWS::Redshift::ClusterSubnetGroup': 'RedshiftClusterSecurityGroup.svg',
    #'AWS::Route53::HealthCheck': 'Route53HealthCheck.svg',
    'AWS::Route53::HostedZone': 'Networking/Networking_AmazonRoute53_hostedzone.svg',
    #'AWS::Route53::RecordSet': 'Route53RecordSetGroup.svg',
    #'AWS::Route53::RecordSetGroup': 'Route53RecordSetGroup.svg',
    'AWS::S3::Bucket': 'Storage & Content Delivery/Storage-Content-Delivery_AmazonS3_bucket.svg',
    #'AWS::S3::BucketPolicy': 'S3BucketPolicy.svg',
    'AWS::SDB::Domain': 'General/General_AWScloud.svg',
    'AWS::SNS::Topic': 'Messaging/Messaging_AmazonSNS_topic.svg',
    #'AWS::SNS::TopicPolicy': 'SNSTopicPolicy.svg',
    'AWS::SQS::Queue': 'Application Services/Application-Services_AmazonSQS.svg',
    #'AWS::SQS::QueuePolicy': 'SQSQueuePolicy.svg',
    'AWS::SSM::Document': 'Management Tools/ManagementTools_AmazonEC2SystemsManager_documents.svg',
    'AWS::WorkSpaces::Workspace': 'Enterprise Applications/Enterprise-Applications_AmazonWorkSpaces.svg'
}
